[font]
normal = { family = "FiraCode Nerd Font", style = "Regular" }
bold = { family = "FiraCode Nerd Font", style = "Bold" }
italic = { family = "FiraCode Nerd Font", style = "Italic" }
bold_italic = { family = "FiraCode Nerd Font", style = "Bold Italic" }

size = 12.0

[font.offset]
x = 0
y = 0

[font.glyph_offset]
x = 0
y = 0

[colors]
[colors.primary]
background = "#1a1b26"  # Dark background
foreground = "#c0caf5"  # Light blue foreground (text)

[colors.normal]
black   = "#32344a"  # Darker gray
red     = "#f7768e"  # Soft red
green   = "#9ece6a"  # Green
yellow  = "#e0af68"  # Yellow
blue    = "#7aa2f7"  # Blue
magenta = "#bb9af7"  # Magenta
cyan    = "#7dcfff"  # Cyan
white   = "#a9b1d6"  # Light gray

[colors.bright]
black   = "#545c7e"  # Gray
red     = "#ff7a93"  # Brighter red
green   = "#b9f27c"  # Bright green
yellow  = "#ff9e64"  # Brighter yellow
blue    = "#7aa2f7"  # Same blue as normal
magenta = "#bb9af7"  # Same magenta as normal
cyan    = "#7dcfff"  # Same cyan as normal
white   = "#c0caf5"  # Bright white

[colors.cursor]
text = "#1a1b26"     # Cursor text (contrasting background)
cursor = "#c0caf5"   # Cursor color

[colors.selection]
text = "#c0caf5"        # Selected text color
background = "#364a82"  # Selection background

[window]
# decorations="Buttonless"
decorations="none"
dynamic_padding = true

# Optional: Tab colors if using a terminal multiplexer like tmux
# [colors.tabs]
# active_background = "#3d59a1"   # Active tab background (deep blue)
# active_foreground = "#c0caf5"   # Active tab text (light blue)
# inactive_background = "#1a1b26" # Inactive tab background (dark)
# inactive_foreground = "#545c7e" # Inactive tab text (gray)
